### PR TITLE
Removed spaces

### PR DESCRIPTION
**Pull request by bartrylant**
Maybe it's even better to change "Startdatum" to "Begindatum" or "Beginuur" to "Startuur" for being consistent.

### CODE REVIEW

**Comment by janhenckens** [comment]
I agree, "Begindatum" would be better. Feel free to change the translation in this PR :)

**Comment by janhenckens** [comment]
Thanks! Do you need this with some urgency or can it wait until the next release?

**Comment by bartrylant** [comment]
Next release is fine.

**Comment by janhenckens** [comment]
Ok, thanks for the PR!

**Pull request merged**
